
// Products
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const RECEIVE_SINGLE_PRODUCT = 'RECEIVE_SINGLE_PRODUCT';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const RECEIVE_REVIEWS = 'RECEIVE_REVIEWS';
